# Generated by Django 5.0.1 on 2024-01-24 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_product_category_alter_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor",
                to="core.vendor",
            ),
        ),
    ]
