# Generated by Django 5.0.1 on 2024-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_productimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="life",
            field=models.CharField(
                blank=True, default="100 Days", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufactury_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                blank=True, default="Organic", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.CharField(blank=True, default="10", max_length=100, null=True),
        ),
    ]
