# Generated by Django 5.0.1 on 2024-01-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_product_life_product_manufactury_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="return_days",
            field=models.CharField(default="10", max_length=100),
        ),
    ]
