# Generated by Django 5.0.1 on 2024-01-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_vendor_return_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="return_days",
            field=models.CharField(default="100", max_length=100),
        ),
    ]
