# Generated by Django 5.0.1 on 2024-01-24 10:45

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_vendor_return_days"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
