# Generated by Django 5.0.1 on 2024-02-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_cartorder_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="mobile_no",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
