# Generated by Django 5.0.1 on 2024-08-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_address_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufactury_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='5,000', max_digits=999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default='7,000', max_digits=999999999999),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default='+12345678', max_length=100),
        ),
    ]
