# Generated by Django 5.0.1 on 2024-02-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us"},
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
